# Generated by Django 3.0.3 on 2021-09-23 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20210922_1813'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='ganre',
            new_name='genre',
        ),
    ]
